# Generated by Django 5.0.9 on 2024-11-04 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pets", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="pet",
            name="profile_image",
            field=models.ImageField(blank=True, upload_to="medias/"),
        ),
    ]
