# Generated by Django 5.0.9 on 2024-11-08 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pets", "0003_alter_household_name_alter_owner_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pet",
            name="household",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
