# Generated by Django 5.0.9 on 2024-11-08 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pets", "0004_alter_pet_household"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="booking",
            name="household",
        ),
    ]
