# Generated by Django 5.0.9 on 2024-11-08 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pets", "0006_remove_owner_household"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Household",
        ),
    ]
