# Generated by Django 5.0.9 on 2024-11-22 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pets", "0009_remove_booking_pet"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pet",
            name="household",
        ),
    ]
