# Generated by Django 5.0.9 on 2024-11-22 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pets", "0011_household_owner_household_pet_household"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="household",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bookings",
                to="pets.household",
            ),
        ),
    ]
