# Generated by Django 5.0.9 on 2024-12-04 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pets", "0015_alter_booking_bonus_rate_alter_booking_household_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="bonus_rate",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="booking",
            name="household",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bookings",
                to="pets.household",
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bookings",
                to="pets.owner",
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="pet",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bookings",
                to="pets.pet",
            ),
        ),
        migrations.AlterField(
            model_name="owner",
            name="household",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="owners",
                to="pets.household",
            ),
        ),
        migrations.AlterField(
            model_name="pet",
            name="household",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pets",
                to="pets.household",
            ),
        ),
        migrations.AlterField(
            model_name="pet",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pets",
                to="pets.owner",
            ),
        ),
    ]
