# Generated by Django 5.0.9 on 2024-12-11 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pets", "0016_alter_booking_bonus_rate_alter_booking_household_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="booking",
            name="owner",
        ),
    ]
