# Generated by Django 5.0.9 on 2024-12-11 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pets", "0017_remove_booking_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bookings",
                to="pets.owner",
            ),
        ),
    ]
