# Generated by Django 5.0.9 on 2024-12-12 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pets", "0020_pet_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="booking",
            name="pet",
        ),
        migrations.AddField(
            model_name="booking",
            name="pet",
            field=models.ManyToManyField(related_name="bookings", to="pets.pet"),
        ),
    ]
