# Generated by Django 5.0.9 on 2024-12-12 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pets", "0022_rename_pet_booking_pets"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="booking",
            name="pets",
        ),
    ]
