# Generated by Django 5.0.9 on 2024-12-12 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pets", "0023_remove_booking_pets"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pet",
            name="profile_image",
            field=models.ImageField(blank=True, upload_to="profile_imgs/"),
        ),
    ]
