# Generated by Django 5.0.9 on 2024-12-20 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pets", "0024_alter_pet_profile_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("postcode", models.CharField(max_length=7)),
                ("prefecture", models.CharField(max_length=100)),
                ("city", models.CharField(max_length=100)),
                ("town", models.CharField(blank=True, max_length=100, null=True)),
                ("street_address", models.CharField(max_length=255)),
                (
                    "owner",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="address",
                        to="pets.owner",
                    ),
                ),
            ],
        ),
    ]
