# Generated by Django 5.0.9 on 2024-12-20 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pets", "0025_address"),
    ]

    operations = [
        migrations.RenameField(
            model_name="address",
            old_name="street_address",
            new_name="street",
        ),
    ]
