# Generated by Django 5.0.9 on 2024-12-20 11:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pets", "0027_alter_address_street"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="owner",
            name="name",
            field=models.CharField(max_length=250),
        ),
        migrations.AddConstraint(
            model_name="owner",
            constraint=models.UniqueConstraint(
                fields=("name", "user"), name="unique_owner_name_per_user"
            ),
        ),
    ]
