# Generated by Django 5.0.9 on 2024-12-20 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pets", "0028_alter_owner_name_owner_unique_owner_name_per_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="postcode",
            field=models.CharField(max_length=8),
        ),
    ]
