# Generated by Django 5.0.9 on 2024-12-20 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pets", "0031_delete_medication"),
    ]

    operations = [
        migrations.AddField(
            model_name="pet",
            name="medication_instructions",
            field=models.TextField(
                blank=True,
                help_text="Provide instructions on the medication's dosage, frequency, and any special requirements.",
                max_length=1000,
                null=True,
            ),
        ),
    ]
