# Generated by Django 5.0.9 on 2024-12-20 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pets", "0032_pet_medication_instructions"),
    ]

    operations = [
        migrations.AddField(
            model_name="pet",
            name="instruction_manual",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
