# Generated by Django 5.0.9 on 2024-12-22 05:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pets", "0033_pet_instruction_manual"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="household",
            constraint=models.UniqueConstraint(
                fields=("name", "user"), name="unique_household_name_per_user"
            ),
        ),
        migrations.AddConstraint(
            model_name="pet",
            constraint=models.UniqueConstraint(
                fields=("name", "user"), name="unique_pet_name_per_user"
            ),
        ),
    ]
