# Generated by Django 5.0.9 on 2024-12-22 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pets", "0034_household_unique_household_name_per_user_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="pet",
            name="unique_pet_name_per_user",
        ),
    ]
